apiVersion: v1
kind: Service
metadata:
  name: clasificadorialink-service
spec:
  selector:
    app: clasificadorialink
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer